version: "3.9"

services:
    db:
        image: postgres:14.5-alpine
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: rssaggregator
            POSTGRES_USER: rssaggregator
            POSTGRES_PASSWORD: rssaggregator
        ports:
            - "19999:5432"

volumes:
    db_data:
